"""Create courses table

Revision ID: b641cb18408b
Revises: 
Create Date: 2025-10-02 14:34:24.647953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b641cb18408b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('canvas_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('course_code', sa.String(length=100), nullable=True),
    sa.Column('workflow_state', sa.String(length=50), nullable=True),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_students', sa.Integer(), nullable=True),
    sa.Column('enrollment_term_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_courses_active_lookup', 'courses', ['workflow_state', 'name'], unique=False)
    op.create_index('idx_courses_canvas_id', 'courses', ['canvas_id'], unique=True)
    op.create_index('idx_courses_workflow_state', 'courses', ['workflow_state'], unique=False)
    op.create_index(op.f('ix_courses_canvas_id'), 'courses', ['canvas_id'], unique=True)
    op.create_index(op.f('ix_courses_workflow_state'), 'courses', ['workflow_state'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_courses_workflow_state'), table_name='courses')
    op.drop_index(op.f('ix_courses_canvas_id'), table_name='courses')
    op.drop_index('idx_courses_workflow_state', table_name='courses')
    op.drop_index('idx_courses_canvas_id', table_name='courses')
    op.drop_index('idx_courses_active_lookup', table_name='courses')
    op.drop_table('courses')
    # ### end Alembic commands ###
